# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CommitX' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CommitX
    pod 'Alamofire', '~> 4.7'
    pod 'AlamofireImage', '~> 3.5'
    pod 'AlamofireObjectMapper', '~> 5.2'
    pod 'RealmSwift'

end
